import { SiteHeader } from "@/components/site-header";
import { SkillSubnav } from "@/components/skill-subnav";
import { Card } from "@/components/ui/card";

export default async function PreviewPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  return (
    <div className="flex min-h-screen flex-col bg-bg">
      <SiteHeader />
      <SkillSubnav skillId={id} active="preview" />

      <main
        id="main"
        className="mx-auto w-full max-w-7xl flex-1 px-4 py-8 md:px-8"
      >
        <header className="mb-6">
          <h1 className="text-2xl font-semibold tracking-tight">
            Compiled preview
          </h1>
          <p className="mt-1 text-sm text-fg-muted">
            Side-by-side rendered Markdown and raw skills.md source.
          </p>
        </header>

        <div className="grid gap-4 lg:grid-cols-2">
          <Card className="p-6">
            <p className="text-xs font-semibold uppercase tracking-wide text-fg-muted">
              Rendered
            </p>
            <div className="mt-3 h-[60vh] rounded-md bg-bg-muted" />
            <p className="mt-3 text-xs text-fg-subtle">
              Real Markdown rendering arrives in Phase 3 (react-markdown +
              rehype-sanitize).
            </p>
          </Card>
          <Card className="p-6">
            <p className="text-xs font-semibold uppercase tracking-wide text-fg-muted">
              skills.md source
            </p>
            <div className="mt-3 h-[60vh] rounded-md bg-bg-muted font-mono" />
            <p className="mt-3 text-xs text-fg-subtle">
              Generated by the graph compiler — read-only.
            </p>
          </Card>
        </div>
      </main>
    </div>
  );
}
