// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/skills/[id]/review" | "/become-a-creator" | "/browse" | "/c/[slug]" | "/c/all" | "/chat/[handle]" | "/checkout" | "/checkout/success" | "/creator/dashboard" | "/creator/earnings" | "/creator/listing" | "/creator/persona" | "/creator/preview" | "/creator/settings" | "/creator/subscribers" | "/creator/upload" | "/creator/vault" | "/dashboard" | "/dashboard/earnings" | "/dashboard/reviews" | "/dashboard/skills" | "/dashboard/skills/[id]" | "/dashboard/skills/new" | "/dashboard/webhooks" | "/expert/[handle]" | "/explore" | "/library" | "/library/[license-id]" | "/library/[license-id]/vault" | "/occupations/[handle]/[slug]" | "/personas/[handle]/[slug]" | "/s/[handle]/[slug]" | "/search" | "/settings/account" | "/settings/api-tokens" | "/settings/billing" | "/sign-in" | "/sign-up" | "/u/[handle]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/skills/[id]/review": { "id": string; }
  "/become-a-creator": {}
  "/browse": {}
  "/c/[slug]": { "slug": string; }
  "/c/all": {}
  "/chat/[handle]": { "handle": string; }
  "/checkout": {}
  "/checkout/success": {}
  "/creator/dashboard": {}
  "/creator/earnings": {}
  "/creator/listing": {}
  "/creator/persona": {}
  "/creator/preview": {}
  "/creator/settings": {}
  "/creator/subscribers": {}
  "/creator/upload": {}
  "/creator/vault": {}
  "/dashboard": {}
  "/dashboard/earnings": {}
  "/dashboard/reviews": {}
  "/dashboard/skills": {}
  "/dashboard/skills/[id]": { "id": string; }
  "/dashboard/skills/new": {}
  "/dashboard/webhooks": {}
  "/expert/[handle]": { "handle": string; }
  "/explore": {}
  "/library": {}
  "/library/[license-id]": { "license-id": string; }
  "/library/[license-id]/vault": { "license-id": string; }
  "/occupations/[handle]/[slug]": { "handle": string; "slug": string; }
  "/personas/[handle]/[slug]": { "handle": string; "slug": string; }
  "/s/[handle]/[slug]": { "handle": string; "slug": string; }
  "/search": {}
  "/settings/account": {}
  "/settings/api-tokens": {}
  "/settings/billing": {}
  "/sign-in": {}
  "/sign-up": {}
  "/u/[handle]": { "handle": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
