// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/skills/[id]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills/[id]/review">> = Specific
  const handler = {} as typeof import("../../app/admin/skills/[id]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/become-a-creator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/become-a-creator">> = Specific
  const handler = {} as typeof import("../../app/become-a-creator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/browse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse">> = Specific
  const handler = {} as typeof import("../../app/browse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/c/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/c/[slug]">> = Specific
  const handler = {} as typeof import("../../app/c/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/c/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/c/all">> = Specific
  const handler = {} as typeof import("../../app/c/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat/[handle]">> = Specific
  const handler = {} as typeof import("../../app/chat/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/success">> = Specific
  const handler = {} as typeof import("../../app/checkout/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/dashboard">> = Specific
  const handler = {} as typeof import("../../app/creator/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/earnings">> = Specific
  const handler = {} as typeof import("../../app/creator/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/listing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/listing">> = Specific
  const handler = {} as typeof import("../../app/creator/listing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/persona/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/persona">> = Specific
  const handler = {} as typeof import("../../app/creator/persona/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/preview">> = Specific
  const handler = {} as typeof import("../../app/creator/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/settings">> = Specific
  const handler = {} as typeof import("../../app/creator/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/subscribers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/subscribers">> = Specific
  const handler = {} as typeof import("../../app/creator/subscribers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/upload">> = Specific
  const handler = {} as typeof import("../../app/creator/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator/vault">> = Specific
  const handler = {} as typeof import("../../app/creator/vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/earnings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reviews">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/skills/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/skills/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/skills/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/skills/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/skills/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/skills/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/skills">> = Specific
  const handler = {} as typeof import("../../app/dashboard/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webhooks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expert/[handle]">> = Specific
  const handler = {} as typeof import("../../app/expert/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/library/[license-id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library/[license-id]">> = Specific
  const handler = {} as typeof import("../../app/library/[license-id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/library/[license-id]/vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library/[license-id]/vault">> = Specific
  const handler = {} as typeof import("../../app/library/[license-id]/vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/library">> = Specific
  const handler = {} as typeof import("../../app/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/occupations/[handle]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/occupations/[handle]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/occupations/[handle]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/personas/[handle]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personas/[handle]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/personas/[handle]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/s/[handle]/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/s/[handle]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/s/[handle]/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account">> = Specific
  const handler = {} as typeof import("../../app/settings/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/api-tokens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/api-tokens">> = Specific
  const handler = {} as typeof import("../../app/settings/api-tokens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing">> = Specific
  const handler = {} as typeof import("../../app/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in">> = Specific
  const handler = {} as typeof import("../../app/sign-in/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up">> = Specific
  const handler = {} as typeof import("../../app/sign-up/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[handle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[handle]">> = Specific
  const handler = {} as typeof import("../../app/u/[handle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
